<?php
/**
 * validate.php — License key revocation endpoint
 * ================================================
 * Deploy this on any PHP 7.4+ host. Configure VALIDATION_URL and
 * ONLINE_CHECK_ENABLED in licenseValidator.js to point here.
 *
 * What this does:
 *   - Accepts POST { key: "PAYLOAD.SIGNATURE" }
 *   - Checks the payload against a revocation list
 *   - Double-checks server-side expiry (belt + suspenders)
 *   - Returns { valid: true/false, reason: "..." }
 *
 * What this does NOT do:
 *   - Verify the Ed25519 signature (that runs in the client — no private key here)
 *   - Store analytics or usage data (add that yourself if needed)
 *
 * SUPABASE EDGE FUNCTION ALTERNATIVE
 * -----------------------------------
 * If you prefer a Supabase edge function (Deno/TypeScript), create
 * supabase/functions/validate/index.ts with this content:
 *
 *   const REVOKED: string[] = [
 *     // paste payload portions of revoked keys here
 *   ];
 *
 *   Deno.serve(async (req) => {
 *     if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type' } });
 *     const { key = '' } = await req.json();
 *     const dot = key.lastIndexOf('.');
 *     if (dot < 1) return Response.json({ valid: false, reason: 'Invalid key format' });
 *     const payload = key.slice(0, dot);
 *     if (REVOKED.includes(payload)) return Response.json({ valid: false, reason: 'License revoked' });
 *     try {
 *       const json    = atob(payload.replace(/-/g,'+').replace(/_/g,'/') + '==');
 *       const data    = JSON.parse(json);
 *       if (data.expires && new Date(data.expires) < new Date()) return Response.json({ valid: false, reason: 'License expired' });
 *     } catch { return Response.json({ valid: false, reason: 'Invalid payload' }); }
 *     return Response.json({ valid: true, reason: 'OK' }, { headers: { 'Access-Control-Allow-Origin': '*' } });
 *   });
 *
 * Then deploy with: supabase functions deploy validate
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Preflight
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['valid' => false, 'reason' => 'Method not allowed']);
    exit;
}

// ─── Revocation list ──────────────────────────────────────────────────────────
// To revoke a key: take the PAYLOAD portion (everything before the final dot)
// and add it to this array. The key will be blocked on the next online check.
//
// Example:
//   'eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJhcHAiOiJBcHAifQ'
$REVOKED_PAYLOADS = [
    // 'payload_portion_of_key_to_revoke',
];

// ─── Request parsing ──────────────────────────────────────────────────────────
$raw  = file_get_contents('php://input');
$body = json_decode($raw, true);
$key  = trim($body['key'] ?? '');

if (!$key) {
    echo json_encode(['valid' => false, 'reason' => 'No key provided']);
    exit;
}

// Strip whitespace that might have been added during copy-paste
$key = preg_replace('/\s+/', '', $key);

// Split on the last dot
$dotPos = strrpos($key, '.');
if ($dotPos === false || $dotPos === 0 || $dotPos === strlen($key) - 1) {
    echo json_encode(['valid' => false, 'reason' => 'Invalid key format']);
    exit;
}

$payload = substr($key, 0, $dotPos);

// ─── Revocation check ─────────────────────────────────────────────────────────
if (in_array($payload, $REVOKED_PAYLOADS, true)) {
    echo json_encode(['valid' => false, 'reason' => 'License has been revoked']);
    exit;
}

// ─── Server-side expiry double-check ──────────────────────────────────────────
// Decode base64url payload and verify expiry server-side
// (the client already does this, but checking here prevents clock-manipulation attacks)
$b64    = strtr($payload, '-_', '+/') . str_repeat('=', (4 - strlen($payload) % 4) % 4);
$json   = base64_decode($b64);
$data   = $json ? json_decode($json, true) : null;

if ($data === null) {
    // Payload decoded but wasn't valid JSON — still let signature check happen client-side
    // (this shouldn't occur for keys generated by keyGenerator.html)
    echo json_encode(['valid' => false, 'reason' => 'Invalid payload encoding']);
    exit;
}

if (!empty($data['expires'])) {
    try {
        $expiry = new DateTimeImmutable($data['expires'] . ' 00:00:00');
        $today  = new DateTimeImmutable('today');
        if ($expiry < $today) {
            echo json_encode(['valid' => false, 'reason' => 'License expired on ' . $data['expires']]);
            exit;
        }
    } catch (Exception $e) {
        // Malformed date — let the client handle it
    }
}

// ─── All checks passed ────────────────────────────────────────────────────────
echo json_encode(['valid' => true, 'reason' => 'OK']);
